suffix_surfaces:
  ZN:
    - ZN
    - GALVANIZED
    - GALV
    - 镀锌
  CE:
    - NACE
    - CE
    - ANTI-H2S
    - ANTI-HIC

# 镀锌和抗硫材质白名单
suffix_enabled_codes:
  ZN:
    - 20ZN
    - A105ZN
    - Q235BZN
  CE:
    - 20CE
    - A105CE
    - CF415KCE
    - WPBCE
    - Q245RCE

common_materials:
  "20":
    - 20
    - 20#
    - 20号钢
    - 锻20
  "304":
    - S30408
    - SF304
    - 06Cr19Ni10
    - 304
    - WP304
    - F304
    - TP304
  "316L":
    - S31603
    - F316L
    - 022Cr17Ni12Mo2
    - WP316L
    - SF316L
    - TP316L
    - 316L
  "304L":
    - S30403
    - SF304L
    - WP304L
    - 304L
    - F304L
    - TP304L
    - 022Cr19Ni10
    - S304L
  "A105":
    - A105
  "CF415":
    - CF415
  "WPB":
    - WPB
  "321":
    - S32168
    - SF321
    - 06Cr18Ni11Ti
    - F321
    - X6CrNiTi18-10
    - 1.4541
    - WP321
    - TP321
  "CF415K":
    - CF415K
  "2205":
    - SF2205
    - 2205
    - S32205
    - S22053
    - WPS32205
    - F2205
  "Q235B":
    - Q235B
    - Q235-B
  "A106":
    - A106
  "20G":
    - 20G
  "WPL6":
    - WPL6
  "Q245R":
    - Q245R
  "20/PTFE":
    - 20/PTFE
    - PTFE Lined 20
    - 20+PTFE
    - 20#/PTFE
    - PTFE/20
    - PTFE/20#
  "16Mn":
    - 16Mn
  "15CrMo":
    - 15CrMo
  "15CrMoG":
    - 15CrMoG
  "L245":
    - L245
  "A333":
    - A333
  "A105N":
    - A105N
  "AF12G":
    - AF12G
  "WP11":
    - WP11
  "FRP/PVC":
    - FRP/PVC
  "LF485K2":
    - LF485K2
  "20/衬胶":
    - 20/衬胶
    - 20#/衬胶
  "TA2":
    - TA2
  "Q345E":
    - Q345E
    - Q345-E
  "316":
    - 06Cr17Ni12Mo2
    - 316
    - F316
    - SUS 316
    - S31608
    - TP316
    - SS316
    - 6Cr17Ni12Mo2
  "12Cr5MoNT":
    - 12Cr5MoNT
  "CF370":
    - CF370
  "16MnD":
    - 16MnD
  "347H":
    - F347H
    - WP347H
    - TP347H
  "304H":
    - F304H
    - S30409
    - 304H
    - 07Cr19Ni10
  "16MnDG":
    - 16MnDG
