# ============================================================
# 系统自动缓存 (由系统自动维护，请勿手动修改)
# ============================================================

classification_cache:
  name:
    水平三通: 水平三通
    三通水平: 水平三通
    三通垂直上翻: 三通
    电缆桥架水平三通: 桥架
    桥架四通: 桥架
    变径接头: 等径三通
    线槽三通: 线槽
    水平四通: 四通
    线槽弯头: 线槽
    电缆桥架水平弯通: 水平弯通
    直通: 桥架
    线槽四通: 四通
    垂直四通: 四通
    槽盒三通平: 三通
    线槽变径接头: 线槽
    槽盒四通: 四通
    电缆桥架: 桥架
    金属线槽: 线槽
    电缆汇线槽: 汇线槽
    电气桥架: 桥架
    电缆桥架槽盒: 槽盒
    电缆桥架弯头: 桥架
    电缆桥架三通: 三通
  material:
    铝镁合金: 铝合金
    镀锌钢制: 镀锌钢
    高分子复合: 复合型
    热浸锌: 镀锌
    高分子复合材质: 复合型
    铝合金超级: 铝合金
  type:
    槽盒式槽式: 槽式
    梯级式梯级式: 梯级式
    梯级: 梯级式
    梯式槽盒式: 槽盒式
    槽盒: 槽盒式
name:
  垂直三通: VT
  梯式桥架: QJ
  三通: SQ
  四通: ST
